### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by alexdiliberto** [html-next/ember-gestures#118]
Tracing a memory leak back to this addon from my app. Not doing anything weird here, basically just loading up an blank/default Unit test and seeing that the Ember container is not being freed from the heap due held references on a `click` and `touchend` handler which traces back to this addon's `event_dispatcher.js` here: https://github.com/html-next/ember-gestures/blob/v1.1.0/addon/event_dispatcher.js#L69

![screen shot 2018-09-13 at 11 40 51 am](https://user-images.githubusercontent.com/666459/45499200-ec509600-b749-11e8-9c35-a39e80e3ea4d.png)

Here you can see the events still attached to `document.body` after the application instance has been torn down after the test

![screen shot 2018-09-13 at 11 40 39 am](https://user-images.githubusercontent.com/666459/45499201-ec509600-b749-11e8-9404-288fa71000c7.png)

For the root cause of the issue, `get(this, 'rootElement')` is the whole `document.body` inside the `_fastFocus` method, but then on teardown `get(this, 'rootElement')` is `#ember-testing` inside the `willDestroy` hook.

![screen shot 2018-09-13 at 11 49 26 am](https://user-images.githubusercontent.com/666459/45499834-253d3a80-b74b-11e8-9444-66c7d7317ee1.png)
![screen shot 2018-09-13 at 11 49 44 am](https://user-images.githubusercontent.com/666459/45499835-253d3a80-b74b-11e8-9d97-16aebbedfcae.png)

**Comment by crixx** [comment]
@alexdiliberto did you already find a workaround or a fix?

**Comment by runspired** [comment]
what is `rootElement` passed to the `setup` hook at this point? https://github.com/html-next/ember-gestures/blob/v1.1.0/addon/event_dispatcher.js#L162

I'm thinking we need to either `super` first or need to pass the `rootElement` arg into the call to `_fastFocus`

**Comment by crixx** [comment]
@runspired  The passed ```rootElement``` is ```#ember-testing```. I checked the previous version of this file (the one in relese 1.0.0) and there the ```rootElement``` passed into the setup method is just saved to the instance. That part got lost during the jquery-elimination. I openend a pull request bringing it back. Please feel free to review it or to give me some hints how to test it correctly 🤔 
https://github.com/html-next/ember-gestures/pull/119
