### ISSUE TITLE
Usage with native class components

### ISSUE THREAD

**Issue by MartinMalinda** [html-next/ember-gestures#127]
If my component is not created via EmberObject.extend, but rather with a native class, I don't have an option to pass a mixin.

Is there an alternative other than reverting to `extend` ?

```
export default class MyComponent extends Component {
```

**Comment by eriktrom** [comment]
try this:  (should still work, been about 6 months, reopen if i'm wrong)

```js
export default class PersonComponent extends Component.extend(FullNameMixin, OtherMixin) {
// ...
}
```
