### ISSUE TITLE
Support Octane (glimmer/modifiers)

### ISSUE THREAD

**Issue by DuBistKomisch** [html-next/ember-gestures#131]
Thought I'd open this since 3.15/Octane is officially out and recommended, and this is the only addon in my app which gets in the way.

The only real issue as far as I can see is the requirement of the recognizer mixin. I know you can still use `extend` with an Ember Component as in https://github.com/html-next/ember-gestures/issues/127 but this doesn't work with a Glimmer Component.

From my understanding, the appropriate alternative would be a "modifier" which gets added to the element in the template instead. Perhaps I'm missing something to do with Managers though which makes it not that simple.

**Comment by knownasilya** [comment]
This would be awesome.

**Comment by knownasilya** [comment]
Oh, looks like it's available `<div {{recognize-gesture "pan" "tap" "press" }}>`. Can close this I think.

**Comment by knownasilya** [comment]
Looks like jQuery's `trigger` doesn't trigger the event on element with the modifier:

```js
const $toggle = $('.x-toggle-container');

$toggle.trigger('panright');
```

Where the element is 

```hbs
<span
  {{recognize-gesture 'pan'}}
  {{on 'panleft' this.handlePanLeft}}
  {{on 'panright' this.handlePanRight}}
>

**Comment by eriktrom** [comment]
use native custom event, dispatch

jquery is broken for all events,  and with pointer events/ui events - even more so... 

(i am assuming you have figured this out, probably by asking runspired, so closing, if not, feel free to reopen).

**Comment by DuBistKomisch** [comment]
FWIW `{{recognize-gesture}}` was what I needed, thanks! I'm using this branch to avoid deprecation spam at the moment: https://github.com/html-next/ember-gestures/pull/137
