### ISSUE TITLE
should a `click()` handler on a component work?

### ISSUE THREAD

**Issue by kbullaughey** [html-next/ember-gestures#34]
Should we expect traditional style click handlers on components work?

If I have a component that doesn't use any `ember-gestures` recognizers or mixins as follows:

```
Ember.Component.extend({
    click: function() {
        console.log('click');
    }
});
```

The handler never gets called on iOS, but it does on my mac laptop running Chrome. I was under the impression that this is still supposed to work.

**Comment by runspired** [comment]
It absolutely should still work, this may be an issue with hammer-time configuration?

**Comment by kbullaughey** [comment]
I noticed it before up updated from 0.3.3 to 0.4.0 (which involved switching to the new hammertime configuration) and then I updated and the problem was still there. So it seems it was a problem with both the old configuration and the new one.

What's strange is that in my main project, there are lots of places where this works just fine. And then there are some that don't, and I can't figure out the difference. But when I went to see if it was `ember-gestures` related by building a test interaction in the dummy app, it didn't work there in that particular case. I don't know the reason. 

You're welcome to try out my pull request and see if you an reproduce the problem on your end. It would help reassure me I'm not crazy.

**Comment by runspired** [comment]
Only thing I can think of is you are using click somewhere there is also a `tap` or `pan` recognizer and hammerjs is killing the click (it calls prevent default on source events on some browsers).  Will investigate.

**Comment by kbullaughey** [comment]
Hm...this just keeps getting weirder. I made a new ember app and the only thing I did was install my component with a `click` handler and I get the same behavior. Works on desktop, not on iPhone. So it seems it's not `ember-gestures`.

**Comment by kbullaughey** [comment]
Actually, I guess this is the expected behavior. Ember doesn't expect touch devices to fire click events. I guess this is what your AST walker is fore? So I want to correct my earlier comment that I think it's not `ember-gestures`, I think it is, but I'll need to learn more before I could posit a solution.

**Comment by runspired** [comment]
@kbullaughey it's possible that the component reopen in `ember-hammertime` isn't functioning properly.

**Comment by runspired** [comment]
It is under test coverage for making sure the style is added when `click` is present, but there could be something else going wrong with hooking everything up.

**Comment by eriktrom** [comment]
U guys are having all the fun today. 😤

I'll be playing with this tonight and over the weekend. Let u know my findings as well.

**Comment by eriktrom** [comment]
Closing -  b/c ember-hammertime, which provides the mixin for adding `touch-action: manipulation` and the ast parser for doing the same has been through some recent updates and so this is hopefully is no longer an issue (its been updated as a dep in the most recent release of this project)

if there are still issues anyone experiences, feel free to re-open
