### ISSUE TITLE
Unintuitive first experience

### ISSUE THREAD

**Issue by machty** [html-next/ember-gestures#47]
I feel like either the documentation starts you off on the wrong foot, or perhaps the API is missing the Ember API sheen, but it took me a while to figure out what I was doing wrong, so I figured I'd leave some comments here:
- the README should probably lead with a very basic example of adding a gesture handler to a component rather than leading in directly with a definition of Recognizers vs Managers, which should probably be toward the bottom of the README in an Advanced/Architecture section
- I just needed to add swipeRight, eventually figured out how to get a `swipe` handler to get called, but the event doesn't seem to contain any info as to which direction was swiped, which seems counter to https://github.com/hammerjs/hammer.js/wiki/Getting-Started#event-data
- I ended up having to generate my owner swiperight recognizer, which felt kind of overkill for such a common thing?

All in all it felt like a lot of work to just slap a swipeRight back behavior onto my ember-concurrency deck, and I still can't tell if I'm doing it right. I think some API polish and a friendlier intro to the README might help.

**Comment by sparkrevolutions** [comment]
+1 Im reading the readme over a few times and to be honest, still don't understand where to start!

I know this isn't the best place to ask, but could somebody just confirm after creating a recogniser - can you only utilise gestures by making individual components?

**Comment by runspired** [comment]
I'm very open to PRs for docs / guides / readme improvements.  When it comes to gestures, I'm mostly focused on improving the underlying library (hammer.js) these days, and won't have energy for any serious work here until that is done.

**Comment by eriktrom** [comment]
API changes are welcome and up for discussion. Closing for now, as this has gone stale. Thanks @machty for your honest feedback.
