### ISSUE TITLE
Each loop

### ISSUE THREAD

**Issue by sparkrevolutions** [html-next/ember-gestures#49]
Hi, great work with this. Starting to get used to it... But what is meant by this statement in the readme?

"_Don't add recognizers to components created within an {{#each}} loop. Use a recognizer at the base of the each instead._"

What do you mean by "_Base of the each instead_". If it is outside the each, then it would not work for each "item" in the loop. If its inside the each, then that goes against the first part of the statement...

I have come across an issue with another addon (ember-masonry-grid) when using this and have a suspicion it may have something to do with that message.

Thanks in advance

**Comment by sparkrevolutions** [comment]
Actually, my issue was related to some clashing CSS and resolved now. But still, what is meant by the tip?

**Comment by snc** [comment]
It means that if you have a `List` component which contains several `ListItem` components, you add the `RecognizerMixin` etc. to the `List` component and the event handlers like `panStart` to the `ListItem` component.
