### ISSUE TITLE
hammer.js vs hammerjs in bower dependencies

### ISSUE THREAD

**Issue by ChristopheVandePoel** [html-next/ember-gestures#70]
I think there's an issue when looking at how hammer.js is currently installed by bower. I'm not sure if this changed recently, but hammerjs is installed in the bower_components/hammerjs/ directory if you install it manually. 

Because ember-gestures installs bower in the bower_components/hammer.js/ directory, there is potential for installing the library twice, and because ember-gestures expects hammerjs to be in that hammer.js/ subdirectory, it can be very confusing when you get the following error:

Error: ENOENT: no such file or directory, stat '... tmp\source_map_concat-input_base_path-1Z4L8OIl.tmp\0\bower_components\hammer.js\hammer.js

This happened after manually rebuilding bower dependencies from a sourceproject, and got me stuck for a long while because I hadn't noticed the period in the hammer.js directory.

Can't this be updated by simply updating the bower dependency in ember-gestures and altering where ember-gestures searches for it?

**Comment by arjunkathuria** [comment]
This seems correct.

<img width="778" alt="screen shot 2016-11-24 at 9 43 08 am" src="https://cloud.githubusercontent.com/assets/12858057/20586766/41d96ee0-b22d-11e6-969b-5d3aaa050204.png">

for Bower there seems to be 2 versions floating around.
- hammer.js => older 2015 version, 2.0.6 i believe.
- hammerjs => 2016 version but not the modernized one, April 2016, 2.0.7/8

but both when followed lead to the main hammer repo.
https://github.com/EightMedia/hammer.js.git redirects to  https://github.com/hammerjs/hammer.js
ember-gestures currently uses the first one.

@runspired RFC for switching to hammerjs to maintain naming consistency with the npm module [hammerjs].

**Comment by rwwagner90** [comment]
We now use npm for hammerjs, so I think this is no longer an issue. If it is, please feel free to reopen!
