### ISSUE TITLE
Handle upstream changes to EventDispatcher private API's.

### ISSUE THREAD

**Issue by rwjblue** [html-next/ember-gestures#75]
This changed a bit upstream in https://github.com/emberjs/ember.js/pull/14784, figured you might want to detect and handle (to be cross version compat).

**Comment by rwjblue** [comment]
https://github.com/html-next/ember-gestures/blob/develop/addon/event_dispatcher.js#L166 needs to be updated to pass in the view registry

**Comment by runspired** [comment]
Thanks!
