### ISSUE TITLE
How i enable fastclick?

### ISSUE THREAD

**Issue by villander** [html-next/ember-gestures#78]
How i enable fastclick? in your readme said just that `When installed via ember install ember-gestures, it will additionally install ember-hammertime to use for "fastclick" support.`

I need set anything pro fastclick to work?

**Comment by rwwagner90** [comment]
It's automatic. Please reach out if you are having issues getting it to work

**Comment by eriktrom** [comment]
If u just want fastclick support use ember-hammertime alone. Ember gestures includes ember-hammertime but other things as well u likely don't need if fastclick is ur goal.  

Just FYI.

**Comment by eriktrom** [comment]
Also the latest ember-hammertime is not included with the npm published version of this module, and contains substantial bug fixes. Highly recommend just using latest of ember hammertime due to this as well.
