### ISSUE TITLE
Generating a recognizer places the new file in wrong path

### ISSUE THREAD

**Issue by jeanduplessis** [html-next/ember-gestures#80]
If you create a new recognizer with the following command, `ember g recognizer test` it generates the file in an invalid path.

Console output from above command:
```     
installing recognizer
  create app/ember-gestures/test/recognizer.js
```

The correct path should be: `app/ember-gestures/recognizers/test.js`

**Comment by eriktrom** [comment]
u mind submitting a pr if u have a chance - thanks for filing the issue 👍
