### ISSUE TITLE
Why last commits on master are not released yet ?

### ISSUE THREAD

**Issue by msalahz** [html-next/ember-gestures#91]
Why last commits on master are not released yet ?

**Comment by jeanduplessis** [comment]
@eriktrom & @runspired it would be great if we can get the last few commits released. 
Currently 0.4.4 doesn't play nice with Ember 2.12.x or later and is blocking our project's upgrade path to new versions.
Let me know if I can help with anything.

**Comment by msalahz** [comment]
I'm welling to help as well

**Comment by msalahz** [comment]
Anybody there ?

**Comment by eriktrom** [comment]
sorry for the delay - I will release today - I need to cross check ember-hammertime - as its a dep that has had activity i haven't looked at yet - and run whats on master locally to ensure we're g2g - thanks all for the reminder 👍

**Comment by DuBistKomisch** [comment]
:+1: bump, still seems to work fine as is but getting heaps of deprecation warnings

**Comment by eriktrom** [comment]
has anyone tested this fully by npm linking - including npm linking ember-hammertime - i haven't gotten to it - if anyone wants to vouch that it all works when tied together i'll release - also not sure if ember-hammertime needs a release as well

sorry for the delay - those are the q's i need to ensure to pull the trigger if anyone wants to connect those dots

(if not, i should have time by EOW)

**Comment by msalahz** [comment]
Hi @eriktrom, I have time soon just tell me what you meant exactly by `npm linking` and why its important ?

**Comment by eriktrom** [comment]
Thanks! The main thing I want to check is that running ember install ember-gestures works for new apps and doesn't break apps that aren't locking their deps. I believe a dep, ember-hammertime, installed by the blueprint now points to npm instead of bower. I'm not sure if that dep is published to both, and if so I need to verify it gets installed correctly, for old and new consumers. Nothing too big. I was on vacation and then real busy, so bottom of the list this has been for me. Appologies everyone. 

Thanks a bunch if u can confirm or deny.

**Comment by eriktrom** [comment]
Also hammertime and hammerjs - is everything going through npm now and if so does it install and boot. 😉

**Comment by eriktrom** [comment]
@rwwagner90 - i believe the good work u did on sat morning is what i was waiting on, thankyou - ping when https://github.com/html-next/ember-hammertime/pull/37 passes, or u pull the trigger here, all good either way

(fwiw - https://github.com/ember-animation/liquid-fire/blob/master/index.js#L87-L118 is another way to handle the fastboot guard i happened to see this week, throwing that out if it helps in anyway)

again, gratzi 👍

**Comment by rwwagner90** [comment]
@eriktrom that issue is resolved. I need to bump the versions on here, then we can release. I'll get it updated now.

There is a package out now for the fastboot guards you can use. I used it in ember-flatpick. https://github.com/shipshapecode/ember-flatpickr/blob/master/index.js#L20

**Comment by rwwagner90** [comment]
@eriktrom I think I got everything good to go for a release. Are you on the ember slack?

**Comment by jeanduplessis** [comment]
@rwwagner90 / @eriktrom Would you guys mind releasing a new version on NPM with all the recent merged commits?

**Comment by rwwagner90** [comment]
Just release 0.4.5
